#!/bin/bash

VPN_PORT="1197"
DEFAULT_RTABLE='lan'

DEFAULT_GW="$(ip route | grep 'default' | awk '{print $3}')"
DEFAULT_DEV="$(ip route | grep 'default' | awk '{print $5}')"
DEFAULT_SOURCE="$(ip addr show ${DEFAULT_DEV} | grep -m 1 -e 'inet\s' | awk '{print $2}' | sed 's/\/.*//')"
DEFAULT_NET="$(ip route | grep "dev ${DEFAULT_DEV}" | awk -v device="${DEFAULT_DEV}" '$3 == device {print $1}')"
DEFAULT_NET_SOURCE="$(ip route | grep "dev ${DEFAULT_DEV}" | awk -v device="${DEFAULT_DEV}" '$3 == device {print $9}')"

echo 200 ${DEFAULT_RTABLE} >> /etc/iproute2/rt_tables
echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 0 > /proc/sys/net/ipv4/conf/eth0/rp_filter
ip route add default via ${DEFAULT_GW} dev ${DEFAULT_DEV} as ${DEFAULT_SOURCE} table ${DEFAULT_RTABLE}
ip route add ${DEFAULT_NET} dev ${DEFAULT_DEV} as ${DEFAULT_NET_SOURCE} table ${DEFAULT_RTABLE}
ip rule add fwmark 1 table ${DEFAULT_RTABLE}

#CLEAN IPTABLES
iptables -P OUTPUT DROP
iptables -P INPUT DROP
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X
iptables -N VPN
iptables -A VPN -j DROP

#MANGLE - PRE
iptables -t mangle -A PREROUTING -j CONNMARK --restore-mark
iptables -t mangle -A PREROUTING -m mark ! --mark 0 -j RETURN
iptables -t mangle -A PREROUTING -p tcp -m tcp --dport 8443 -j MARK --set-mark 1


#MANGlE - OUTPUT
iptables -t mangle -A OUTPUT -d 10.0.0.0/14 -j MARK --set-mark 1

#MANGLE - POST
iptables -t mangle -A POSTROUTING -j CONNMARK --save-mark

#NAT - POST
iptables -t nat -A POSTROUTING -o ${DEFAULT_DEV} -j SNAT --to-source ${DEFAULT_SOURCE}

#VPN
iptables -I VPN -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -I VPN -o tap+ -j ACCEPT
iptables -I VPN -o tun+ -j ACCEPT

#INPUT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -i tun+ -j VPN
iptables -A INPUT -i tap+ -j VPN
#INPUT RULES
iptables -A INPUT -i eth0 -p tcp -m tcp --dport 8443 -j ACCEPT
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
#iptables -A INPUT -j LOG --log-prefix "INPUT: DROPPING: "

#OUTPUT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -o tap+ -j VPN
iptables -A OUTPUT -o tun+ -j VPN
#OUTPUT RULES
iptables -A OUTPUT -d 209.222.18.218/32 -p icmp -j ACCEPT
iptables -A OUTPUT -d 209.222.18.218/32 -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.218/32 -p tcp -m tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -p icmp -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -d 209.222.18.222/32 -p tcp -m tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp -m owner --cmd-owner openvpn -j ACCEPT 2>/dev/null &&
iptables -A OUTPUT -p udp -m owner --cmd-owner openvpn -j ACCEPT || {
    iptables -A OUTPUT -p tcp -m tcp --dport ${VPN_PORT} -j ACCEPT
    iptables -A OUTPUT -p udp -m udp --dport ${VPN_PORT} -j ACCEPT; }
#HANDLE LOCAL CONNECTIONS
#RTORRENT GUI
iptables -A OUTPUT ! -o tun+ -p tcp -m tcp --sport 8443 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT ! -o tap+ -p tcp -m tcp --sport 8443 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
#RSYNC SERVER
iptables -A OUTPUT ! -o tun+ -p tcp -m tcp --dport 873 -j ACCEPT
iptables -A OUTPUT ! -o tap+ -p tcp -m tcp --dport 873 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 53 -j ACCEPT
#iptables -A OUTPUT -j LOG --log-prefix "OUTPUT: DROPPING: "
